### ISSUE TITLE
Feature request: There should be option for prepare project. 

### ISSUE THREAD

**Issue by govi2010** [NativeScript/nx#31]
Like we are having option for `debug`  and `run`, We must have option for `prepare`

I am facing issue when I am adding build command on my Azure CD/ CI.

**Comment by govi2010** [comment]
I have changed code which works
https://github.com/govi2010/nx/commit/5ecbb4672bca038c12f6d0c01cfa405f59a9e4e4

**Comment by rob4226** [comment]
Prob can close this. I added a `prepare` option a few months ago with PR https://github.com/NativeScript/nx/pull/34

**Comment by govi2010** [comment]
@rob4226  closed.
