### ISSUE TITLE
[Question] How to set 'nativescript/nx' environment for development and contributing?

### ISSUE THREAD

**Issue by marckassay** [NativeScript/nx#47]
Currently, I have a forked cloned repo of 'nativescript/nx' on my filesystem. Using Yarn (v1), I did the following after I cloned:

```sh
cd nx
yarn install
yarn build
cd dist/packages/nx
yarn link
```

And in my test project, I executed, `yarn link @nativescript/nx -D`. But there seems to be an issue with linking that causes a "Cannot find module @angular-devkit/architect" error coming from within Nx code. 

So I'm curious what is the ideal way to go about this?

**Comment by NathanWalker** [comment]
@marckassay sorry for late reply, best way is to use [`verdaccio`](https://www.npmjs.com/package/verdaccio) and publish it locally to test changes out.
