### ISSUE TITLE
3.0.12 creates duplicate options and breaks builds

### ISSUE THREAD

**Issue by joshcomley** [NativeScript/nx#48]
Running:

    npx nx build nativescript-isite:ios:dev --bundle --for-device  --copy-to ./build.ipa --provision xxx-xxx-xxx-xxx

Produces:

    ns build ios --no-hmr --env.uglify --env.production --for-device --release --provision=xxx-xxx-xxx-xxx --copy-to=./build.ipa --env.replace=./src/environments/environment.ts:./src/environments/environment.development.ts --force --bundle --copy-to ./build.ipa --provision xxx-xxx-xxx-xxx

`copy-to` and `provision` are duplicated. I do not have these in my NX config files, I only pass them via command line as they are generated at build time.

This did not happen with `3.0.11` and the build worked.

Many thanks,
Josh

**Comment by NathanWalker** [comment]
Thanks for reporting this - can you try putting ‘=‘ with your extra args so like this:

```
npx nx build nativescript-isite:ios:dev --for-device  --copy-to=./build.ipa --provision=xxx-xxx-xxx-xxx
```

**Comment by NathanWalker** [comment]
@joshcomley lemme know if that solved it for you ^ - if so we can add some additional checks to still allow both forms to work likely.

**Comment by NathanWalker** [comment]
Another thing to check is ensure using @nativescript/nx 3.0.13 latest - just added an enforcement on some options which can never become an array (singular only) - to prevent value mangling always ensure use `--flag=value` format and if the value has spaces as `provision` can often use single quotes `--provision='match AppStore my.bundle.com'`
