### ISSUE TITLE
@nativescript/nx must be used inside an Nx workspace. Create a workspace first. https://nx.dev

### ISSUE THREAD

**Issue by grizlizli** [NativeScript/nx#71]
Hi,

Hope you are doing well.

I tried created a project with Nx and when I try to add Nativescript app, I get this error:

`@nativescript/nx must be used inside an Nx workspace. Create a workspace first. https://nx.dev`

However, the project was generated with Nx and the Nx workspace does exist...

Here's the list of commands I used:

```
npx create-nx-workspace@latest
cd my-app-name
npm install --save-dev @nx/js
npx nx g @nx/js:init
npm install --save-dev @nativescript/nx
npx nx g @nativescript/nx:app my-app-name-mobile
```

Node version: v18.14.0

**Comment by NathanWalker** [comment]
Hi @grizlizli Nx 17 was released 2 days ago which could be related. You can try this in meantime:

npx create-nx-workspace@16.10.0

and then same steps.

**Comment by grizlizli** [comment]
I tried with version 16.10.0, same error. :(
@NathanWalker

**Comment by NathanWalker** [comment]
Thanks again @grizlizli Nx 17+ with all the fixes was just published:
https://github.com/NativeScript/nx/releases/tag/17.0.0

Same steps, please post back if any further issue.

**Comment by grizlizli** [comment]
It looks good now. Thanks!
